server:
  port: 8095

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: comment-service
          uri: lb://COMMENT-SERVICE
          predicates:
            - Path=/api/comments/**
        - id: post-service
          uri: lb://POST-SERVICE
          predicates:
            - Path=/api/posts/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowed-headers: '*'
            allowedMethods: GET, POST, PUT, DELETE
            allowed-origins: '*'
            max-age: 3600

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
