spring:
  application:
    name: POST-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/demopostdb
    username: root
    password: 258025

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8081


