spring:
  application:
    name: COMMENT-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/democommentdb
    username: root
    password: 258025
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8082



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

# Optional: to show the instance in Eureka UI
instance:
  prefer-ip-address: true
